export const LAYER = {
  ADD: 'LAYER_ADD',
  REMOVE: 'LAYER_REMOVE',
  GET_INFO:'LAYER_GET_INFO',
  MOVE_LAYER:'LAYER_MOVE_LAYER',
  CLEAR_DRAG:'LAYER_CLEAR_DRAG'
};

export const MAP = {
  GET_CONFIG: 'MAP_GET_CONFIG',
  SET_VIEW: 'MAP_SET_VIEW',
  SET_VIEW2: 'MAP_SET_VIEW2',
  SET_RESOLUTION: 'MAP_SET_RESOLUTION',
  ZOOM_IN: 'MAP_ZOOM_IN',
  ZOOM_OUT: 'MAP_ZOOM_OUT',
  SET_ROTATION: 'MAP_SET_ROTATION'
};
