export const LAYER = {
  ADD: 'LAYER_ADD',
  REMOVE: 'LAYER_REMOVE',
  GET_INFO:'LAYER_GET_INFO',
  MOVE_LAYER:'LAYER_MOVE_LAYER',
  CLEAR_DRAG:'LAYER_CLEAR_DRAG'
};

export const MAP = {
  GET_CONFIG: 'MAP_GET_CONFIG',
  EXTENT_TO_RESOLUTION: 'MAP_EXTENT_TO_RESOLUTION',
  SET_VIEW: 'MAP_SET_VIEW'
};
