

export const MAP = {
  SET_VIEW: 'MAP_SET_VIEW',
  ADD_LAYER: 'MAP_ADD_LAYER',
  ADD_SOURCE: 'MAP_ADD_SOURCE',
  REMOVE_LAYER: 'MAP_REMOVE_LAYER',
  REMOVE_SOURCE: 'MAP_REMOVE_SOURCE',
  UPDATE_LAYER: 'MAP_UPDATE_LAYER',
};
